# Generated by Django 4.2.8 on 2024-02-09 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('phno', models.IntegerField()),
                ('mailid', models.TextField()),
                ('address', models.TextField()),
                ('purpose', models.CharField(max_length=100)),
                ('mater', models.BooleanField(default=False)),
                ('coursename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finaltaskapp.course')),
                ('deptname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finaltaskapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaltaskapp.department'),
        ),
    ]
