# Generated by Django 4.2.8 on 2024-02-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltaskapp', '0002_alter_order_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mater',
            field=models.BooleanField(choices=[('pen', 'pen'), ('exam pappers', 'exam pappers'), ('notebook', 'notebook')], max_length=100),
        ),
    ]
