# Generated by Django 4.2.8 on 2024-02-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltaskapp', '0003_alter_order_mater'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='a',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='mater',
            field=models.BooleanField(choices=[('pen', 'pen'), ('exam pappers', 'exam pappers'), ('notebook', 'notebook')], default=False, max_length=100),
        ),
    ]
