# Generated by Django 4.2.8 on 2024-03-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltaskapp', '0004_order_a_alter_order_mater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purpose',
            field=models.CharField(choices=[('for enquiry', 'for enquiry'), ('return', 'return'), ('place order', 'place order')], default=False, max_length=100),
        ),
    ]
