# Generated by Django 4.2.8 on 2024-03-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finaltaskapp', '0006_alter_order_mailid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='a',
            new_name='PEN',
        ),
    ]
