# Generated by Django 4.2.8 on 2024-03-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finaltaskapp', '0007_rename_a_order_pen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='PEN',
            new_name='pen',
        ),
    ]
