# Generated by Django 4.2.8 on 2024-03-05 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finaltaskapp', '0008_rename_pen_order_pen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='deptname',
            field=models.ForeignKey(blank=True, help_text='select Department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finaltaskapp.department'),
        ),
    ]
