# Generated by Django 4.2.8 on 2024-03-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltaskapp', '0010_remove_order_mater_order_exam_pappers_order_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], default=False, max_length=100),
        ),
    ]
